#!/bin/sh

# This is a script which installs all the items in His Majesty's Software
# Suite (HMSS).

# Run me with `sh installer` plus any flags, e.g. `sh installer --raspian`.

# Constants.
HMSS_DIR="$HOME/hmss"
PATH_TO_WALLPAPER="$HMSS_DIR/wallpaper.jpg"

# Flags.
raspian_flag="n"
xubuntu_flag="n"

################
# UPDATE FLAGS #
################

for flag in $@; do
    if [ $flag = "--raspian" ]; then
        raspian_flag="y"
    elif [ $flag = "--xubuntu" ]; then
        xubuntu_flag="y"
    fi
done

##########
# BASICS #
##########

# Let's get cracking...
cd $HOME
sudo apt update
sudo apt --yes upgrade

# Install Git.
sudo apt --yes install git

# Install Chromium.
sudo apt --yes install chromium-browser

# Install PIP3.
sudo apt --yes install python3-pip

# Install the extra plugins for Gedit.ech
sudo apt --yes install gedit-plugins

# Change wallpaper.
echo "*** Changing wallpaper... ***"
if [ $raspian_flag = "y" ]; then
    pcmanfm --set-wallpaper $PATH_TO_WALLPAPER
else
    gsettings set org.gnome.desktop.background picture-uri \
        file:///$PATH_TO_WALLPAPER
fi
if [ $? -ne 0 ]; then exit 1; fi
echo "*** Wallpaper changed. ***"
cd $HOME

############
# THE WIKI #
############

if [ ! -d kingdom-of-cyprus ]; then
    # Install SQLite and browser.
    sudo apt --yes install sqlite3
    sudo apt --yes install sqlitebrowser
    # Install NodeJS and NPM.
    sudo apt --yes install nodejs
    sudo apt --yes install npm
    # Download and install the repo.
    git clone https://github.com/tomhosker/kingdom-of-cyprus.git
    cd kingdom-of-cyprus/
    npm install
    cd ..
fi

#####################
# HOSKER'S ALMANACK #
#####################

if [ ! -d hoskers-almanack ]; then
    # Install LaTeX.
    sudo apt --yes install texlive-full
    # Clone the repo.
    git clone https://github.com/tomhosker/hoskers-almanack.git
fi

############
# CHANCERY #
############

if [ ! -d chancery ]; then
    # Download the repo for Formulary A.
    git clone https://github.com/tomhosker/chancery.git
fi

if [ ! -d chancery-b ]; then
    # Download and install the repo for Formulary B.
    git clone https://github.com/tomhosker/chancery-b.git
    cd chancery-b/
    sh install_externals
    cd ..
fi

########
# HGMJ #
########

if [ ! -d hgmj ]; then
    git clone https://github.com/tomhosker/hgmj.git
    # Install third party software.
    cd hgmj
    sh install_3rd_party
    cd ..
fi

#####################
# OTHER THIRD PARTY #
#####################

# Install Inkscape.
sudo apt --yes install inkscape

# That's it!
echo "***** HMSS installed successfully! *****"
