#!/bin/sh

# This is a script which installs all the items in His Majesty's Software
# Suite (HMSS).

# Run me with `sh installer` plus any flags, e.g. `sh installer --raspian`.

# Constants.
HMSS_DIR="$HOME/hmss"
PATH_TO_WALLPAPER_DIR="$HMSS_DIR/wallpaper"
DEFAULT_PATH_TO_WALLPAPER="$PATH_TO_WALLPAPER_DIR/default.jpg"
CHROME_STEM="https://dl.google.com/linux/direct/"
CHROME_DEB="google-chrome-stable_current_amd64.deb"

# OS flags.
os_flag="ubuntu"
thunderbird_no="0"

################
# UPDATE FLAGS #
################

# Update OS flags.
for flag in $@; do
    if [ $flag = "--raspian" ]; then os_flag="raspian"
    elif [ $flag = "--chromeos" ]; then os_flag="chromeos"
    elif [ $flag = "--other-os" ]; then os_flaf="other"
    fi
done

# Update Thunderbird flags.
for flag in $@; do
    if [ $flag = "--t1" ]; then thunderbird_no="1"; break
    elif [ $flag = "--t2" ]; then thunderbird_no="2"; break
    elif [ $flag = "--t3" ]; then thunderbird_no="3"; break
    elif [ $flag = "--t4" ]; then thunderbird_no="4"; break
    elif [ $flag = "--t5" ]; then thunderbird_no="5"; break
    fi
done

##########
# BASICS #
##########

# Let's get cracking...
echo "***** Installing HMSS... *****"
cd $HOME
sudo apt update
sudo apt --yes upgrade
sudo apt --yes install software-properties-common

# Install Git.
sudo apt --yes install git

# Install Chrome.
if [ $os_flag != "chromeos" ]; then
    wget $CHROME_STEM/$CHROME_DEB
    sudo apt --yes install ./$CHROME_DEB
fi

# Install PIP3 and PyLint.
sudo apt --yes install python3-pip
sudo apt --yes install pylint

# Install the extra plugins for Gedit.
sudo apt --yes install gedit-plugins

# Change wallpaper.
if [ $thunderbird_no != "0" ]; then
    path_to_wallpaper="$PATH_TO_WALLPAPER_DIR/wallpaper_t$thunderbird_no.png"
else
    path_to_wallpaper="$PATH_TO_WALLPAPER_DIR/default.png"
fi
if [ $os_flag = "ubuntu" ]; then
    gsettings set org.gnome.desktop.background picture-uri \
        file:///$path_to_wallpaper
elif [ $os_flag = "raspian" ]; then
    pcmanfm --set-wallpaper $path_to_wallpaper
fi

############
# THE WIKI #
############

if [ ! -d kingdom-of-cyprus ]; then
    # Install SQLite and browser.
    sudo apt --yes install sqlite3
    sudo apt --yes install sqlitebrowser
    # Install NodeJS and NPM.
    sudo apt --yes install nodejs
    sudo apt --yes install npm
    # Download and install the repo.
    git clone https://github.com/tomhosker/kingdom-of-cyprus.git
    cd kingdom-of-cyprus/
    npm install
    cd ..
fi

#####################
# HOSKER'S ALMANACK #
#####################

if [ ! -d hoskers-almanack ]; then
    # Install LaTeX.
    sudo apt --yes install texlive-full
    # Clone the repo.
    git clone https://github.com/tomhosker/hoskers-almanack.git
fi

############
# CHANCERY #
############

if [ ! -d chancery ]; then
    # Download the repo for Formulary A.
    git clone https://github.com/tomhosker/chancery.git
fi

if [ ! -d chancery-b ]; then
    # Download and install the repo for Formulary B.
    git clone https://github.com/tomhosker/chancery-b.git
    cd chancery-b/
    sh install_3rd_party
    cd ..
fi

########
# HGMJ #
########

if [ ! -d hgmj ]; then
    git clone https://github.com/tomhosker/hgmj.git
    # Install third party software.
    cd hgmj
    sh install_3rd_party
    cd ..
fi

#####################
# OTHER THIRD PARTY #
#####################

# Install Inkscape.
sudo apt --yes install inkscape

# Install Nomacs.
sudo add-apt-repository --yes ppa:nomacs/stable
sudo apt update
sudo apt --yes install nomacs

# Install some programs necessary on a Chromebook.
if [ $os_flag = "chromeos" ]; then
    sudo apt --yes install nautilus
    sudo apt --yes install eog
fi

# That's it!
echo "***** HMSS installed. *****"
